name: CICD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

jobs:
  ci:
    permissions: write-all
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Commit
        run: |
          pip install pre-commit
          pip install mypy
          pre-commit --version
          pre-commit install
          pre-commit run --all-files

  cd:
    needs: [ci]
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Compile'
        run: |
          pip install -r src/pipeline_futbol/requirements.txt
          python -B src/pipeline_futbol/pipeline.py

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          project_id: 'gcp-pipeline-demo-505709'
          workload_identity_provider: 'projects/849549998884/locations/global/workloadIdentityPools/github-identity-pool/providers/github-provider'
          service_account: 'gcp-pipeline-service-account@gcp-pipeline-demo-505709.iam.gserviceaccount.com'

      - name: 'Register'
        run: |
          curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F tags=latest \
          -F content=@pipeline_futbol.yaml \
          https://us-central1-kfp.pkg.dev/gcp-pipeline-demo-505709/artifact-repository
