name: CICD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

jobs:
  ci:
    permissions: write-all
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Commit
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit install
          pre-commit run --all-files 

  cd:
    needs: [ci]
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Compile'
        run: |
          pip install -r src/pipeline_futbol/requirements.txt
          python -B src/pipeline_futbol/pipeline.py

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          project_id: 
          workload_identity_provider: 
          service_account:

      - name: 'Register'
        run: |
          curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F tags=latest \
          -F content=@pipeline_futbol.yaml \
          ${{ vars.PIPELINE_REPOSITORY }}

